name: business_card_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  qr_flutter: 4.1.0
  share_plus: ^10.0.2
  image: ^4.1.0
  path_provider: ^2.0.0
  loading_animation_widget: ^1.2.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Heading
      fonts:
        - asset: assets/fonts/Heading-Pro-ExtraBold-Italic.ttf
    - family: pricedown_bl
      fonts:
        - asset: assets/fonts/pricedown_bl.ttf
    - family: yukari
      fonts:
        - asset: assets/fonts/yukari.ttf
    - family: a
      fonts:
        - asset: assets/fonts/a.otf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
